# fly.toml app configuration file generated for hogflix-sessions-service-snowy-cloud-6788 on 2025-01-23T13:36:41-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "posthog-demo-sessionhog"
primary_region = "lax"

[env]
  PORT = "3000"
  NODE_ENV = "production"
  TZ = "America/Los_Angeles"

[processes]
  app = "node app/sessions_server.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.ports]]
  port = 80
  handlers = ["http"]

[[http_service.ports]]
  port = 443
  handlers = ["tls", "http"]

[http_service.concurrency]
  type = "connections"
  hard_limit = 1000
  soft_limit = 800

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
