# fly.toml app configuration file generated for hogflix-sessions-service-snowy-cloud-6788 on 2025-01-23T13:36:41-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hogflix-sessions-service-snowy-cloud-6788'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'immediate'

[env]
  NODE_ENV = 'production'
  TZ = 'America/Chicago'

[processes]
  cron = 'node app/sessions_server.js'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  ports = []
  processes = ['cron']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
