[build]
builder = "NIXPACKS"
buildCommand = "pnpm install"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.env]
NODE_ENV = "production"

engine-strict=true 